### PR TITLE
MacOS Sandboxing

### PR DESCRIPTION
**Pull request by RayBytes**
This is just a draft pull I will keep updating as I now enter beta testing for this profile, as its now entered the stage where it can be used publicly.

If ya'll want to test it out just get the file either from my repo or just look at the changes in this draft pull.

### CODE REVIEW

**Comment by RayBytes** [comment]
Known issues:
- Minecraft versions 1.7> **do not currently work, and will just crash the game**
~~- Audio does not work~~ SOLVED

**Comment by RayBytes** [comment]
Alright I didnt find a way to properly make 1.7 work in the normal profile, so here is the aptley named "Pre 1.6 Patcher".
If you need pre 1.6 you would use this, otherwise you're fine.

```
import sys
import os

sandbox_file = sys.argv[1]
if os.path.isfile(sandbox_file) & sandbox_file.endswith('.sb'):
    with open(sandbox_file, 'r') as file:
        data = file.readlines()
    for line in data:
        if "$HOME" in line:
            data[data.index(line)] = line.replace("$HOME", str(os.getenv("HOME")))
    with open(sandbox_file, 'w') as file:
        file.writelines( data )
else:
    raise FileNotFoundError("Sorry, no sandbox file was found at your given file directory. ")
```

**Comment by getchoo** [comment]
i would like to note `sandbox-exec` is deprecated. please see [this](https://github.com/bazelbuild/bazel/issues/13766) bazel issue, as well as [this](https://forums.swift.org/t/sandbox-exec-is-deprecated/10201) post on the swift forums; i don't think implementing this is a viable long term solution due to this deprecation. a better alternative imo would be following apple's guidance and using their [entitlements system](https://developer.apple.com/documentation/security/app_sandbox)

**Comment by RayBytes** [comment]
> i would like to note `sandbox-exec` is deprecated. please see [this](https://github.com/bazelbuild/bazel/issues/13766) bazel issue, as well as [this](https://forums.swift.org/t/sandbox-exec-is-deprecated/10201) post on the swift forums; i don't think implementing this is a viable long term solution due to this deprecation. a better alternative imo would be following apple's guidance and using their [entitlements system](https://developer.apple.com/documentation/security/app_sandbox)

sandbox-exec has been deprecated since 2020, however it has still being used in system for quite some time. You can see a full list in /Library/Profiles I think. sandbox-exec is also still the backend for the App Sandbox feature in xcode, and theres no sight of it being removed any time soon.

**Comment by getchoo** [comment]
> however it has still being used in system for quite some time

this doesn't mean it will continue to be, nor that we should start using it now. this is what deprecation is supposed to mean: not removed, but unsupported/not recommended.

>  sandbox-exec is also still the backend for the App Sandbox feature in xcode

so why not use intended frontend? i also can't find any sources on this, and logically i don't see why they would be using `sandbox-exec` directly and not bsd's `sandbox`, as the former is meant to be a user facing cli component. futhermore, using entitlements directly would make for a much easier experience in launcher's upstreaming this, as it can be directly integrated with projects as opposed to users being required to launch clients from the cli

**Comment by RayBytes** [comment]
> > however it has still being used in system for quite some time
> 
> this doesn't mean it will continue to be, nor that we should start using it now. this is what deprecation is supposed to mean: not removed, but unsupported/not recommended.
> 
> > sandbox-exec is also still the backend for the App Sandbox feature in xcode
> 
> so why not use intended frontend? i also can't find any sources on this, and logically i don't see why they would be using `sandbox-exec` directly and not bsd's `sandbox`, as the former is meant to be a user facing cli component. futhermore, using entitlements directly would make for a much easier experience in launcher's upstreaming this, as it can be directly integrated with projects as opposed to users being required to launch clients from the cli

the bazel issue which you had talked about, the person who was assigned to the issue also had written this post: https://jmmv.dev/2019/11/macos-sandbox-exec.html. Thats where I had gotten the idea of sandbox-exec being the backend of the app sandboxing too. Regardless, I am pretty sure App Sandbox feature in X Code cannot be applied to minecraft itself, because the language macos apps are written in is with Swift/Obj-C, and I'm pretty sure XCode does not support anything else.

**Comment by RayBytes** [comment]
Actually looking into it, it may be possible to bundle java Apps with XCode, but it does not seem like the cleanest soloution.

**Comment by RayBytes** [comment]
Chrome and Firefox and Apple's bazel are also currently using this tool, so I do not think Apple will suddenly making it fully disappear without any replacement

**Comment by getchoo** [comment]
> Regardless, I am pretty sure App Sandbox feature in X Code cannot be applied to minecraft itself, because the language macos apps are written in is with Swift/Obj-C, and I'm pretty sure XCode does not support anything else.

this wouldn't be needed if you sandbox the launcher itself, which is easy to do with entitlements given that those are still enforced in child processes.

> I do not think Apple will suddenly be making it fully disappear

of course not, it's only deprecated

> without any replacement

[there is a replacement though](https://developer.apple.com/documentation/security/app_sandbox)

**Comment by RayBytes** [comment]
> > Regardless, I am pretty sure App Sandbox feature in X Code cannot be applied to minecraft itself, because the language macos apps are written in is with Swift/Obj-C, and I'm pretty sure XCode does not support anything else.
> 
> 
> 
> this wouldn't be needed if you sandbox the launcher itself, which is easy to do with entitlements given that those are still enforced in child processes.
> 
> 
> 
> > I do not think Apple will suddenly be making it fully disappear
> 
> 
> 
> of course not, it's only deprecated
> 
> 
> 
> > without any replacement
> 
> 
> 
> [there is a replacement though](https://developer.apple.com/documentation/security/app_sandbox)

Once again, how are you going to do this on the launcher since this can only be done in Xcode

**Comment by getchoo** [comment]
> Once again, how are you going to do this on the launcher since this can only be done in Xcode

because it doesn't need xcode? only an entitlements file. prism already has [one](https://github.com/PrismLauncher/PrismLauncher/blob/develop/program_info/App.entitlements) for example and it's packaged with the app [here](https://github.com/PrismLauncher/PrismLauncher/blob/develop/.github/workflows/build.yml#L350)

there is also a more hardened version [here](https://discord.com/channels/1115852272245686334/1117482703143579748/1118343017934360576) in the discord server

**Comment by RayBytes** [comment]
> > Once again, how are you going to do this on the launcher since this can only be done in Xcode
> 
> 
> 
> because it doesn't need xcode? only an entitlements file. prism already has [one](https://github.com/PrismLauncher/PrismLauncher/blob/develop/program_info/App.entitlements) for example and it's packaged with the app [here](https://github.com/PrismLauncher/PrismLauncher/blob/develop/.github/workflows/build.yml#L350)
> 
> 
> 
> there is also a more hardened version [here](https://discord.com/channels/1115852272245686334/1117482703143579748/1118343017934360576) in the discord server

Interesting, Apple docs only talk about through XCode, which I guess is understandable. Also I can't see how you restrict the actual file system in this entitlements system.

**Comment by RayBytes** [comment]
The point of the sandbox is to restrict the file system to only necessary components and libraries

**Comment by RayBytes** [comment]
Looking a bit more into it, it is possible to give access to certain files in the Container. Though I still do not honestly see the benefit of this entitlement system over the profile system. It just seems to be the profile system migrated into XML

**Comment by RayBytes** [comment]
Prism launcher has now also been tested, 3 changes had to be made for support, but now it works. Profile should work for all launchers as long as they do not require different files/resources from the system than the base game.

**Comment by RayBytes** [comment]
This pull is now ready @xyzeva. I've basically done most of the stuff I wanted to do. More pulls will likely just be with more launcher support and more tools added to the patcher for launcher devs and users.

**Comment by RayBytes** [comment]
BTW any MacOS users - please go test the files in this pull.

**Comment by RayBytes** [comment]
Actually, wait. I have an idea to completely eliminate the patcher.

**Comment by RayBytes** [comment]
Alright done

**Pull request merged**
